### ISSUE TITLE
Defect - 401 Unauthorised with Chrome

### ISSUE THREAD

**Issue by Squadz** [itsnubix/laravel-nuxt#1]
**SUMMARY**
401 Error when accessing Register/Login using Chrome, there is no repro with Firefox.

**STEPS TO REPRODUCE**
```
git clone https://github.com/itsnubix/laravel-nuxt
cd laravel-nuxt
npm install --force
composer install
cp .env.example .env
php artisan key:generate
./vendor/bin/sail up -d
./vendor/bin/sail migrate:fresh --seed
npm run dev
```

**OBSERVED RESULT**
GET http://localhost:8000/api/me 401 (Unauthorized)

This issue could only be reproduced with Google Chrome/Chromium.

**EXPECTED RESULT**
Being able to : 
- create an account
- logged in

**ADDITIONAL INFORMATION**
Not related to this issue, but the installation commands from the README might be wrong :
`./vendor/bin/sail artisan migrate:fresh --seed` instead of `php artisan migrate:fresh --seed`

**Comment by kylemilloy** [comment]
Likely will effect all Chromium browsers...tested on Safari and Firefox and it works as expected. I'll look into this...thanks for the report.

**Comment by kylemilloy** [comment]
Change your `SESSION_DOMAIN` from `.localhost` to `localhost` and this should resolve it.
